version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
    restart: on-failure

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"